version: '3'

services:

  frame:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    environment:
      JSON_PLACEHOLDER_URL: https://jsonplaceholder.typicode.com